version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: asyrafduyshart/rust-reverse-proxy:latest
    ports:
      - "3500:3500"
    environment:
      - APP_PORT=8050
      - LISTEN_IP=0.0.0.0
      - CONFIG_SETTING={"log_level":"error","ip_whitelist_url":"http://35.240.165.230/company/whitelist/list/lidodev","ip_check_interval":"30","http":{"servers":[{"root":"static","name":"site2","proxies":[{"proxy_pass":"https://apichallenges.herokuapp.com/mirror/request","proxy_path":"/mirror","retain_path":true,"request_headers":[{"someheader":"Oke"}]}],"listen":"3500"}]},"access_log":"verbose"}